FROM rust:latest

WORKDIR /usr/src/app

# Install cargo-watch for hot-reloading
RUN cargo install cargo-watch

# Install sqlx-cli for migrations
RUN cargo install sqlx-cli --no-default-features --features rustls,postgres

COPY . .

CMD sqlx database create && sqlx migrate run && cargo watch -x "run --bin backend"
