ALTER TABLE rankings
ADD COLUMN timeframe_days INTEGER NOT NULL DEFAULT 30,
ADD COLUMN stars_gained INTEGER NOT NULL DEFAULT 0,
ADD COLUMN star_velocity FLOAT NOT NULL DEFAULT 0.0,
ADD COLUMN growth_ratio FLOAT NOT NULL DEFAULT 0.0,
ADD COLUMN contributors_gained INTEGER NOT NULL DEFAULT 0,
ADD COLUMN contributor_growth FLOAT NOT NULL DEFAULT 0.0,
ADD COLUMN growth_score FLOAT NOT NULL DEFAULT 0.0,
ADD COLUMN contributor_score FLOAT NOT NULL DEFAULT 0.0,
ADD COLUMN maintenance_score FLOAT NOT NULL DEFAULT 0.0;
